specVersion: 1.0.0
name: nodlebalanceindexer
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.1.2
  query:
    name: '@subql/query'
    version: 1.0.0
description: 'nodle Balance Indexer'
repository: 'https://github.com/ipayzone/Nodle-Balance-Indexer'
schema:
  file: ./schema.graphql
network:
  chainId: '0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21'
  endpoint: 'wss://nodle-parachain.api.onfinality.io/ws?apikey=9e5c1537-e0a7-42cb-a2ef-4d7d2899337f'
  dictionary: 'https://api.subquery.network/sq/subquery/nodle-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
